数据操作

In [ ]:
import torch #导入的是torch不能写成pytorch

In [ ]:
#张量表示一个数值组成的数组，数组可以有多个维度
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# 张量的形状
x.shape

torch.Size([12])

In [ ]:
# 张量中元素的总数
x.numel()

12

In [ ]:
# 改张量的形状，不改变元素的的数量和元素值
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

创建一个元素全为 0 的张量（Tensor），括号中的参数表示张量的维度大小，每个数字对应一个维度的长度。

第一个参数 2：表示张量的第 0 维（最外层维度） 大小为 2，即该维度有 2 个元素。

第二个参数 3：表示张量的第 1 维大小为 3，即每个外层元素包含 3 个中层元素。

第三个参数 4：表示张量的第 2 维（最内层维度） 大小为 4，即每个中层元素包含 4 个最内层元素。

因此，torch.zeros(2, 3, 4) 会创建一个形状为 (2, 3, 4) 的三维张量，总元素数量为 2×3×4 = 24 个（均为 0）。

可以理解为：这个张量包含 2 个 "块"[ , ]；每个块又分3个块，即上一个[ , ]中的空里是[ , , ]；每个块再分4个块，即上一个[ , ]中的空里是[ , , , ]

In [ ]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.zeros(2)

tensor([0., 0.])

In [11]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.zeros(2,1)

tensor([[0.],
        [0.]])

In [ ]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [35]:
torch.tensor([3])# 1维，不能写成torch.tensor(3)

tensor([3])

In [13]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])# 2维

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [14]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]]).shape

torch.Size([3, 4])

In [15]:
torch.tensor([[[2,1,4,3],[1,2,3,4],[4,3,2,1]]])# 3维

tensor([[[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]])

In [17]:
torch.tensor([[[2,1,4,3],[1,2,3,4],[4,3,2,1]]]).shape

torch.Size([1, 3, 4])

In [20]:
x = torch.tensor([1,2,4,8])
x

tensor([1, 2, 4, 8])

In [23]:
x = torch.tensor([1.0,2,4,8])# 为后续计算引入浮点数
x

tensor([1., 2., 4., 8.])

tensor之间的基本数学运算是按照元素进行的

In [25]:
y = torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y# **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [26]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [32]:
x = torch.arange(12,dtype=torch.float32).reshape((3,4))# 形状为(3,4)
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [33]:
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])# 形状为(3,4)
y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [36]:
torch.cat((x,y),dim=0)# 第0维是最外围，拼完后形状变成(6,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [37]:
torch.cat((x,y),dim=1)# 拼完后形状变成(3,8)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

torch.cat((x, y), dim=0) 是用于拼接张量的函数，其参数含义如下：

第一个参数 (x, y)：这是一个包含待拼接张量的元组（或列表），表示需要将 x 和 y 这两个张量按照指定维度拼接起来。

注意：x 和 y 必须满足 “除拼接维度外，其他所有维度的大小都相同”，否则会报错。

第二个参数 dim=0：表示拼接的维度，dim=0 即沿着第0维进行拼接。维度的编号从0开始。

In [38]:
x == y #通过逻辑运算符构建二维张量

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [40]:
x.sum() #所有元素加起来的总和，不用管【】

tensor(66.)

即使形状不同，仍然可以通过调用广播机制俩执行按元素操作

In [41]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [42]:
a+b #维度不同，由于广播机制，使得a被复制成3x2的矩阵，b被复制成3x2的矩阵，再相加

tensor([[0, 1],
        [1, 2],
        [2, 3]])

元素的访问

In [43]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [46]:
x[-1],x[1:2],x[1:5]# x[-1]最后一个元素,x[1:2]第一到第二行（第二行不取）,x[1:5]第一到第五行

(tensor([ 8.,  9., 10., 11.]),
 tensor([[4., 5., 6., 7.]]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [48]:
x[1,2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [50]:
x[0:2,:] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [51]:
before = id(y)# id告诉我们对象y在python中的标识号，类似c++的指针
y = y+x
id(y) == before

False

In [52]:
z = torch.zeros_like(y)# 生成一个与输入张量y形状完全相同、但所有元素值均为0的新张量
print('id(z):',id(z))
z[:] = x+y# z中所有元素=x+y中的元素
print('id(z):',id(z))

id(z): 136606467430336
id(z): 136606467430336


In [53]:
#如果后续运算中不重复使用x，可以使用x[:]=x+y或x+=y减少操作内存开销
before = id(x)
x += y
id(x) == before

True

转换为Numpy张量(最常见的操作）

In [56]:
A = x.numpy()
B = torch.tensor(A)
type(x),type(A),type(B)#数据类型

(torch.Tensor, numpy.ndarray, torch.Tensor)

In [62]:
# 将大小为1的张量转换成Python标量
a = torch.tensor([3.5])# 如果a是torch.zeros([2,2])之类的多维，无法转标量
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)