In [1]:
import torch

# 创建5x4的矩阵
A = torch.arange(20).reshape((5,4))
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [2]:
A.T # 转置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [3]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [4]:
B == B.T #对称矩阵的转置前后相等

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [5]:
A = torch.arange(20,dtype=torch.float32).reshape((5,4))
B = A.clone() #分配新内存，把一个A的副本分配给B
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [6]:
A * B # 矩阵按元素乘法（哈达玛积），数学符号是圈里面有个点

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [7]:
a = 2
X = torch.arange(24).reshape(2,3,4)
X, a+X, a*X#数字和矩阵的加法跟哈达玛积也是按照元素算的，类似把一个数，当成跟矩阵同维度且各元素都是这个数的矩阵

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]))

指定求和汇总张量的轴

In [8]:
A = torch.arange(20*2).reshape(2,5,4)
A, A.shape, A.sum()

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 torch.Size([2, 5, 4]),
 tensor(780))

In [9]:
# A.sum()不指定任何维度，会对数组或张量A中的所有元素进行求和，返回一个标量（单一数值）
# 数组的维度索引从0开始，依次对应“最外层维度”到“最内层维度”，对应在（）里的参数，就是从左往右
A_sum_axis0 = A.sum(axis=0)# 指定axis=0，表示沿着第0维进行求和，返回一个降维后的数组/张量，加完了就没这一维了
A_sum_axis0, A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [10]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [11]:
A.sum(axis=[0,1]) # 和A.sum()相同

tensor([180, 190, 200, 210])

In [12]:
A.sum(axis=[0,1]).shape

torch.Size([4])

求均值

In [13]:
A = A.float()#整数型不能求mean，转成浮点才行
A.mean(), A.sum()/A.numel()

(tensor(19.5000), tensor(19.5000))

In [14]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

In [15]:
sum_A = A.sum(axis=1,keepdims=True)
''' keepdims=True：保持求和后的维度数量不变（保留原维度结构）。
  若不设置（默认keepdims=False），求和后会删除该维度
  tensor([[ 40,  45,  50,  55],
      [140, 145, 150, 155]])
  设置为True则会保留该维度，仅将其大小变为1
'''
sum_A

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

In [16]:
A / sum_A # 通过广播机制，让A和sum_A两个形状不匹配的矩阵能做除法，本质是在做归一化，便于后续分析或计算

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [17]:
# A.cumsum(axis=0)是计算数组或张量A沿着第0维的累积和，即从起始位置开始，依次累加当前元素与前面所有元素的总和。
C = torch.tensor([[1, 2, 3, 4],
          [5, 6, 7, 8],
          [9, 10, 11, 12]])
"""
  tensor([[ 1,  2,  3,  4],       # 第0行：自身（无前置元素）
        [ 6,  8, 10, 12],      # 第1行：第0行 + 第1行（1+5=6, 2+6=8, ...）
        [15, 18, 21, 24]])     # 第2行：第0行 + 第1行 + 第2行（6+9=15, 8+10=18, ...）
"""
A.cumsum(axis=0),C.cumsum(axis=0)

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 22., 24., 26.],
          [28., 30., 32., 34.],
          [36., 38., 40., 42.],
          [44., 46., 48., 50.],
          [52., 54., 56., 58.]]]),
 tensor([[ 1,  2,  3,  4],
         [ 6,  8, 10, 12],
         [15, 18, 21, 24]]))

In [18]:
x = torch.tensor([1.0,2,3,4])
y = torch.ones(4,dtype=torch.float32)
#dot点积是相同位置的按元素乘积的和，是个标量
x,y,torch.dot(x,y),x*y

(tensor([1., 2., 3., 4.]),
 tensor([1., 1., 1., 1.]),
 tensor(10.),
 tensor([1., 2., 3., 4.]))

In [19]:
torch.dot(x,y) == torch.sum(x*y)

tensor(True)

In [20]:
# 创建一个2x3的矩阵 (2行3列)
A = torch.tensor([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])

# 创建一个长度为3的向量 (与矩阵的列数匹配)
x = torch.tensor([7.0, 8.0, 9.0])

# 检查维度
print("A的形状:", A.shape)  # 应输出 torch.Size([2, 3])
print("x的形状:", x.shape)  # 应输出 torch.Size([3])

# 执行矩阵与向量的乘法Ax
result = torch.mv(A, x)
print("结果:", result)      # 应输出 tensor([ 50., 122.]) 1*7+2*8+3*9=50
print("结果形状:", result.shape)  # 应输出 torch.Size([2])


A的形状: torch.Size([2, 3])
x的形状: torch.Size([3])
结果: tensor([ 50., 122.])
结果形状: torch.Size([2])


矩阵与向量乘法（torch.mv(A, x)）的元素通用求解公式如下：

设：矩阵 A 为 n×m 维（n 行，m 列），元素表示为 A[i][j]（第 i 行第 j 列）向量 x 为 m 维（长度为 m），元素表示为 x[j]（第 j 个元素）结果向量 result 为 n 维，元素表示为 result[i]（第 i 个元素）则结果向量中第 i 个元素的计算公式为：result[i] = A[i][j]*[j] （j从0取到m-1，求得的乘积之和为result[i]，累加符号打不出）

以之前的示例为例：
result[0] = A[0][0]×x[0] + A[0][1]×x[1] + A[0][2]×x[2]
result[1] = A[1][0]×x[0] + A[1][1]×x[1] + A[1][2]×x[2]

In [22]:
A = torch.tensor([[1.0, 2.0, 3.0],
          [4.0, 5.0, 6.0]])
B = torch.ones(3,4)
torch.mm(A,B)#矩阵乘法

tensor([[ 6.,  6.,  6.,  6.],
        [15., 15., 15., 15.]])

矩阵乘法(平时正常的非前面说的按元素的）AB，可以看作简单的执行多次矩阵和向量乘法，并将结果拼接在一起

In [25]:
u = torch.tensor([3.0,-4.0])
torch.norm(u) # 求她的L2范数，即向量元素的平方和的平方根

tensor(5.)

In [30]:
torch.abs(u).sum() # 求L1范数，表示向量元素的绝对值之和

tensor(7.)

In [31]:
torch.norm(torch.ones((4,9))) # 矩阵的Frobenius范数，是矩阵元素的平方和的平方根

tensor(6.)