In [3]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [7]:
x.requires_grad_(True)  #声明需要存梯度。计算y关于x的梯度之前，需要一个地方存梯度
x.grad # 默认是None
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

调用反向传播函数，自动计算y关于x每个分量的梯度

In [8]:
y.backward()
x.grad # 4x1,4x2,4x3,4x4

tensor([ 0.,  4.,  8., 12.])

In [9]:
x.grad == 4 * x

tensor([True, True, True, True])

In [10]:
# 默认情况下，pytorch会累计梯度
x.grad.zero_() #梯度清零
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

深度学习中，我们的目的不是计算微分矩阵，而是每个批次中每个样本单独计算的偏导数之和

In [11]:
x.grad.zero_()
y = x * x
# 大部分情况是对标量求导，而非向量
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [13]:
x.grad.zero_()
y = x * x
# detach()是张量的一个方法，用于将张量从计算图中分离出来，使其不再再参与梯度计算，也不会保留与其他张量的梯度依赖关系
u = y.detach() # u从计算图中分离，对u操作不会影响梯度，u这里变成了常数
z= u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [14]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [15]:
def f(a):
  b = a * 2
  while b.norm() < 1000:
    b = b * 2
  if b.sum() > 0:
    c = b
  else:
    c = 100 * b
  return c

a = torch.randn(size=(),requires_grad=True)
d = f(a)
d.backward()

a.grad == d/a #通过函数，变量梯度仍能计算

tensor(True)